import type { IDETheme } from './types';

export const githubLight: IDETheme = {
  id: 'github-light',
  name: 'GitHub Light',
  type: 'light',

  cssVars: {
    '--bg-titlebar': '#f6f8fa',
    '--bg-activitybar': '#f6f8fa',
    '--bg-sidebar': '#f6f8fa',
    '--bg-editor': '#ffffff',
    '--bg-panel': '#f6f8fa',
    '--bg-statusbar': '#f6f8fa',
    '--bg-tab-active': '#ffffff',
    '--bg-tab-inactive': '#f6f8fa',
    '--fg-primary': '#24292f',
    '--fg-secondary': '#57606a',
    '--fg-muted': '#8b949e',
    '--accent': '#0969da',
    '--border': '#d0d7de',
    '--bg-hover': '#eaeef2',
    '--bg-selection': '#ddf4ff',
    '--terminal-cursor': '#24292f',
  },

  monacoTheme: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6e7781', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'CF222E' },
      { token: 'string', foreground: '0A3069' },
      { token: 'number', foreground: '0550AE' },
      { token: 'type', foreground: '8250DF' },
      { token: 'function', foreground: '8250DF' },
      { token: 'variable', foreground: '24292F' },
      { token: 'constant', foreground: '0550AE' },
      { token: 'operator', foreground: 'CF222E' },
      { token: 'delimiter', foreground: '24292F' },
      { token: 'tag', foreground: '116329' },
      { token: 'attribute.name', foreground: '0550AE' },
      { token: 'attribute.value', foreground: '0A3069' },
      { token: 'regexp', foreground: '0A3069' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#24292f',
      'editor.lineHighlightBackground': '#f6f8fa',
      'editor.selectionBackground': '#ddf4ff',
      'editorCursor.foreground': '#24292f',
      'editorWhitespace.foreground': '#d0d7de',
      'editorLineNumber.foreground': '#8b949e',
      'editorLineNumber.activeForeground': '#24292f',
      'editorIndentGuide.background': '#d0d7de',
      'editorIndentGuide.activeBackground': '#8b949e',
    },
  },

  terminalTheme: {
    background: '#ffffff',
    foreground: '#24292f',
    cursor: '#24292f',
    black: '#24292f',
    red: '#cf222e',
    green: '#116329',
    yellow: '#4d2d00',
    blue: '#0969da',
    magenta: '#8250df',
    cyan: '#1b7c83',
    white: '#6e7781',
    brightBlack: '#57606a',
    brightRed: '#a40e26',
    brightGreen: '#1a7f37',
    brightYellow: '#633c01',
    brightBlue: '#218bff',
    brightMagenta: '#a475f9',
    brightCyan: '#3192aa',
    brightWhite: '#8b949e',
  },
};
