import type { IDETheme } from './types';

export const monokaiPro: IDETheme = {
  id: 'monokai-pro',
  name: 'Monokai Pro',
  type: 'dark',

  cssVars: {
    '--bg-titlebar': '#221f22',
    '--bg-activitybar': '#19171c',
    '--bg-sidebar': '#221f22',
    '--bg-editor': '#2d2a2e',
    '--bg-panel': '#221f22',
    '--bg-statusbar': '#221f22',
    '--bg-tab-active': '#2d2a2e',
    '--bg-tab-inactive': '#221f22',
    '--fg-primary': '#fcfcfa',
    '--fg-secondary': '#c1c0c0',
    '--fg-muted': '#727072',
    '--accent': '#ffd866',
    '--border': '#403e41',
    '--bg-hover': '#403e41',
    '--bg-selection': '#403e41',
    '--terminal-cursor': '#fcfcfa',
  },

  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '727072', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'FF6188' },
      { token: 'string', foreground: 'FFD866' },
      { token: 'number', foreground: 'AB9DF2' },
      { token: 'type', foreground: 'A9DC76' },
      { token: 'function', foreground: 'A9DC76' },
      { token: 'variable', foreground: 'FCFCFA' },
      { token: 'constant', foreground: 'AB9DF2' },
      { token: 'operator', foreground: 'FF6188' },
      { token: 'delimiter', foreground: 'FCFCFA' },
      { token: 'tag', foreground: 'FF6188' },
      { token: 'attribute.name', foreground: '78DCE8' },
      { token: 'attribute.value', foreground: 'FFD866' },
      { token: 'regexp', foreground: 'FF6188' },
    ],
    colors: {
      'editor.background': '#2d2a2e',
      'editor.foreground': '#fcfcfa',
      'editor.lineHighlightBackground': '#403e41',
      'editor.selectionBackground': '#403e41',
      'editorCursor.foreground': '#fcfcfa',
      'editorWhitespace.foreground': '#403e41',
      'editorLineNumber.foreground': '#727072',
      'editorLineNumber.activeForeground': '#c1c0c0',
      'editorIndentGuide.background': '#403e41',
      'editorIndentGuide.activeBackground': '#727072',
    },
  },

  terminalTheme: {
    background: '#2d2a2e',
    foreground: '#fcfcfa',
    cursor: '#fcfcfa',
    black: '#2d2a2e',
    red: '#ff6188',
    green: '#a9dc76',
    yellow: '#ffd866',
    blue: '#78dce8',
    magenta: '#ab9df2',
    cyan: '#78dce8',
    white: '#fcfcfa',
    brightBlack: '#727072',
    brightRed: '#ff6188',
    brightGreen: '#a9dc76',
    brightYellow: '#ffd866',
    brightBlue: '#78dce8',
    brightMagenta: '#ab9df2',
    brightCyan: '#78dce8',
    brightWhite: '#ffffff',
  },
};
