import type { IDETheme } from './types';

export const oneDarkPro: IDETheme = {
  id: 'one-dark-pro',
  name: 'One Dark Pro',
  type: 'dark',

  cssVars: {
    '--bg-titlebar': '#21252b',
    '--bg-activitybar': '#21252b',
    '--bg-sidebar': '#21252b',
    '--bg-editor': '#282c34',
    '--bg-panel': '#21252b',
    '--bg-statusbar': '#21252b',
    '--bg-tab-active': '#282c34',
    '--bg-tab-inactive': '#21252b',
    '--fg-primary': '#abb2bf',
    '--fg-secondary': '#8b919a',
    '--fg-muted': '#636d83',
    '--accent': '#61afef',
    '--border': '#3e4451',
    '--bg-hover': '#2c313c',
    '--bg-selection': '#3e4451',
    '--terminal-cursor': '#528bff',
  },

  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'C678DD' },
      { token: 'string', foreground: '98C379' },
      { token: 'number', foreground: 'D19A66' },
      { token: 'type', foreground: 'E5C07B' },
      { token: 'function', foreground: '61AFEF' },
      { token: 'variable', foreground: 'E06C75' },
      { token: 'constant', foreground: 'D19A66' },
      { token: 'operator', foreground: '56B6C2' },
      { token: 'delimiter', foreground: 'ABB2BF' },
      { token: 'tag', foreground: 'E06C75' },
      { token: 'attribute.name', foreground: 'D19A66' },
      { token: 'attribute.value', foreground: '98C379' },
      { token: 'regexp', foreground: 'E06C75' },
    ],
    colors: {
      'editor.background': '#282c34',
      'editor.foreground': '#abb2bf',
      'editor.lineHighlightBackground': '#2c313c',
      'editor.selectionBackground': '#3e4451',
      'editorCursor.foreground': '#528bff',
      'editorWhitespace.foreground': '#3b4048',
      'editorLineNumber.foreground': '#636d83',
      'editorLineNumber.activeForeground': '#abb2bf',
      'editorIndentGuide.background': '#3b4048',
      'editorIndentGuide.activeBackground': '#636d83',
    },
  },

  terminalTheme: {
    background: '#282c34',
    foreground: '#abb2bf',
    cursor: '#528bff',
    black: '#282c34',
    red: '#e06c75',
    green: '#98c379',
    yellow: '#e5c07b',
    blue: '#61afef',
    magenta: '#c678dd',
    cyan: '#56b6c2',
    white: '#abb2bf',
    brightBlack: '#5c6370',
    brightRed: '#e06c75',
    brightGreen: '#98c379',
    brightYellow: '#e5c07b',
    brightBlue: '#61afef',
    brightMagenta: '#c678dd',
    brightCyan: '#56b6c2',
    brightWhite: '#ffffff',
  },
};
