import type { IDETheme } from './types';

export const vscodeDark: IDETheme = {
  id: 'vscode-dark',
  name: 'VS Code Dark',
  type: 'dark',

  cssVars: {
    '--bg-titlebar': '#1f1f1f',
    '--bg-activitybar': '#181818',
    '--bg-sidebar': '#181818',
    '--bg-editor': '#1f1f1f',
    '--bg-panel': '#1f1f1f',
    '--bg-statusbar': '#1f1f1f',
    '--bg-tab-active': '#1f1f1f',
    '--bg-tab-inactive': '#181818',
    '--fg-primary': '#cccccc',
    '--fg-secondary': '#acacac',
    '--fg-muted': '#6a6a6a',
    '--accent': '#0078d4',
    '--border': '#2b2b2b',
    '--bg-hover': '#2a2d2e',
    '--bg-selection': '#264f78',
    '--terminal-cursor': '#cccccc',
  },

  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6A9955', fontStyle: 'italic' },
      { token: 'keyword', foreground: '569CD6' },
      { token: 'string', foreground: 'CE9178' },
      { token: 'number', foreground: 'B5CEA8' },
      { token: 'type', foreground: '4EC9B0' },
      { token: 'function', foreground: 'DCDCAA' },
      { token: 'variable', foreground: '9CDCFE' },
      { token: 'constant', foreground: '4FC1FF' },
      { token: 'operator', foreground: 'D4D4D4' },
      { token: 'delimiter', foreground: 'D4D4D4' },
      { token: 'tag', foreground: '569CD6' },
      { token: 'attribute.name', foreground: '9CDCFE' },
      { token: 'attribute.value', foreground: 'CE9178' },
      { token: 'regexp', foreground: 'D16969' },
    ],
    colors: {
      'editor.background': '#1f1f1f',
      'editor.foreground': '#cccccc',
      'editor.lineHighlightBackground': '#2a2d2e',
      'editor.selectionBackground': '#264f78',
      'editorCursor.foreground': '#cccccc',
      'editorWhitespace.foreground': '#3b3b3b',
      'editorLineNumber.foreground': '#6a6a6a',
      'editorLineNumber.activeForeground': '#cccccc',
      'editorIndentGuide.background': '#404040',
      'editorIndentGuide.activeBackground': '#707070',
    },
  },

  terminalTheme: {
    background: '#1f1f1f',
    foreground: '#cccccc',
    cursor: '#cccccc',
    black: '#1e1e1e',
    red: '#f44747',
    green: '#6a9955',
    yellow: '#d7ba7d',
    blue: '#569cd6',
    magenta: '#c586c0',
    cyan: '#4ec9b0',
    white: '#d4d4d4',
    brightBlack: '#808080',
    brightRed: '#f44747',
    brightGreen: '#6a9955',
    brightYellow: '#d7ba7d',
    brightBlue: '#569cd6',
    brightMagenta: '#c586c0',
    brightCyan: '#4ec9b0',
    brightWhite: '#ffffff',
  },
};
